#!/usr/bin/env bash
# adapters/codex/adapter.sh — Codex adapter
# (C) 2026 R-fx Networks <proj@rfxn.com>
# GNU GPL v2
# Sourced by lib/cmd/generate.sh — do not execute directly

# Requires: RDF_HOME, RDF_CANONICAL, RDF_ADAPTERS

_CDX_ADAPTER_DIR="${RDF_ADAPTERS}/codex"
_CDX_OUTPUT_DIR="${_CDX_ADAPTER_DIR}/output"

# Generate AGENTS.md for Codex
# Combines: governance docs + agent roster + command catalog + conventions
cdx_generate_agents_md() {
    local dst_file="${_CDX_OUTPUT_DIR}/AGENTS.md"
    local profiles_dir="${RDF_HOME}/profiles"

    command mkdir -p "$(dirname "$dst_file")"

    {
        echo "# AGENTS.md — rfxn Project Instructions for Codex"
        echo ""
        echo "Generated by \`rdf generate codex\` — do not edit directly."
        echo "Source: rdf/canonical/ + rdf/profiles/"
        echo ""
    } > "$dst_file"

    # Section 1: Project Governance (from active profiles)
    local active
    active="$(rdf_get_active_profiles)"

    {
        echo "## Project Governance"
        echo ""
    } >> "$dst_file"

    while IFS= read -r profile; do
        [[ -z "$profile" ]] && continue
        local gov_file="${profiles_dir}/${profile}/governance.md"
        if [[ -f "$gov_file" ]]; then
            cat "$gov_file" >> "$dst_file"
            echo "" >> "$dst_file"
        fi
    done <<< "$active"

    # Section 2: Agent Roster
    {
        echo "## Agent Roster"
        echo ""
        echo "The following specialized agents are available for dispatch:"
        echo ""
    } >> "$dst_file"

    for agent_file in "${RDF_CANONICAL}/agents"/*.md; do
        [[ -f "$agent_file" ]] || continue
        local agent_name
        agent_name="$(basename "$agent_file" .md)"
        # Extract first non-empty, non-heading line as description
        local agent_desc
        agent_desc="$(sed -n '/^[^#[:space:]]/{ p; q; }' "$agent_file")"
        [[ -z "$agent_desc" ]] && agent_desc="Agent: ${agent_name}"
        echo "- **${agent_name}**: ${agent_desc}" >> "$dst_file"
    done
    echo "" >> "$dst_file"

    # Section 3: Available Commands
    {
        echo "## Available Commands"
        echo ""
        echo "Commands are invoked as slash commands (e.g., \`/mgr\`, \`/audit\`)."
        echo ""
    } >> "$dst_file"

    local cmd_count=0
    for cmd_file in "${RDF_CANONICAL}/commands"/*.md; do
        [[ -f "$cmd_file" ]] || continue
        cmd_count=$((cmd_count + 1))
    done
    echo "Total commands available: ${cmd_count}" >> "$dst_file"
    echo "" >> "$dst_file"

    # Group commands by category
    {
        echo "### Persona Commands"
        echo "mgr, sys-eng, sys-qa, sys-uat, po, scope, sys-sentinel,"
        echo "sys-challenger, sys-ux, sec-eng, fe-qa, fe-uat"
        echo ""
        echo "### Audit Pipeline"
        echo "audit, audit-quick, audit-delta, audit-compile, audit-condense,"
        echo "audit-context, audit-plan, audit-feedback, audit-schema,"
        echo "audit-regression, audit-latent, audit-security, audit-standards,"
        echo "audit-version, audit-cli, audit-docs, audit-config,"
        echo "audit-test-coverage, audit-test-exec, audit-install,"
        echo "audit-build-ci, audit-upgrade, audit-interfaces, audit-modernize"
        echo ""
        echo "### Release"
        echo "rel-prep, rel-ship, rel-merge, rel-notes, rel-chg-dedup,"
        echo "rel-chg-diff, rel-scrub"
        echo ""
        echo "### Project"
        echo "proj-status, proj-health, proj-cross, proj-cross-audit,"
        echo "proj-lib-sync, proj-scaffold"
        echo ""
        echo "### Memory & State"
        echo "mem-save, mem-audit, mem-compact, refresh, reload, status"
        echo ""
    } >> "$dst_file"

    # Verify size is under 32 KiB (Codex default limit)
    local size
    size="$(wc -c < "$dst_file")"
    if [[ "$size" -gt 32768 ]]; then
        rdf_warn "codex: AGENTS.md is ${size} bytes (over 32 KiB Codex limit)"
    fi

    rdf_log "codex: generated AGENTS.md (${size} bytes)"
}

# Generate .codex/config.toml
cdx_generate_config() {
    local dst_dir="${_CDX_OUTPUT_DIR}/.codex"
    local dst_file="${dst_dir}/config.toml"

    command mkdir -p "$dst_dir"

    {
        echo "# Generated by rdf generate codex — do not edit directly"
        echo "# Codex CLI configuration for rfxn projects"
        echo ""
        echo "# Model preference"
        echo "model = \"o4-mini\""
        echo ""
        echo "# Approval mode — suggest for safety"
        echo "approval_mode = \"suggest\""
        echo ""
        echo "# Project doc size limit (bytes)"
        echo "project_doc_max_bytes = 32768"
    } > "$dst_file"

    rdf_log "codex: generated .codex/config.toml"
}

# Generate script files (direct copy)
cdx_generate_scripts() {
    local src_dir="${RDF_CANONICAL}/scripts"
    local dst_dir="${_CDX_OUTPUT_DIR}/scripts"
    local count=0

    command mkdir -p "$dst_dir"

    for src_file in "${src_dir}"/*.sh; do
        [[ -f "$src_file" ]] || continue
        local basename_f
        basename_f="$(basename "$src_file")"
        command cp "$src_file" "${dst_dir}/${basename_f}"
        chmod +x "${dst_dir}/${basename_f}"
        count=$((count + 1))
    done
    rdf_log "codex: generated ${count} script files"
}

# Full Codex generation pipeline
cdx_generate_all() {
    rdf_log "generating Codex adapter output..."
    rdf_require_dir "$RDF_CANONICAL" "canonical directory"

    # Clean output directory
    command rm -rf "$_CDX_OUTPUT_DIR"
    command mkdir -p "$_CDX_OUTPUT_DIR"

    cdx_generate_agents_md
    cdx_generate_config
    cdx_generate_scripts

    rdf_log "Codex generation complete"
}
