#!/usr/bin/env bash
# adapters/agents-md/adapter.sh — AGENTS.md cross-tool adapter
# (C) 2026 R-fx Networks <proj@rfxn.com>
# GNU GPL v2
# Sourced by lib/cmd/generate.sh — do not execute directly

# Requires: RDF_HOME, RDF_CANONICAL, RDF_ADAPTERS, jq

_AMD_ADAPTER_DIR="${RDF_ADAPTERS}/agents-md"
_AMD_OUTPUT_DIR="${_AMD_ADAPTER_DIR}/output"
_AMD_SECTIONS="${_AMD_ADAPTER_DIR}/sections.json"

# Extract a section summary from a governance doc
# This produces a condensed version suitable for AGENTS.md
# Args: $1 = governance file path, $2 = section keyword to extract
_amd_extract_governance_section() {
    local gov_file="$1"
    local keyword="$2"

    if [[ ! -f "$gov_file" ]]; then
        echo "(governance file not found)"
        return 1
    fi

    # Find the section by keyword in headings, extract content until next heading
    local in_section=0
    local lines_out=0
    local max_lines=15

    while IFS= read -r line; do
        # Check for heading containing keyword (case-insensitive)
        local lower_line
        lower_line="$(echo "$line" | tr '[:upper:]' '[:lower:]')"
        local lower_key
        lower_key="$(echo "$keyword" | tr '[:upper:]' '[:lower:]')"

        local heading_re="^##.*${lower_key}"
        if [[ "$lower_line" =~ $heading_re ]]; then
            in_section=1
            continue
        fi

        # Stop at next heading of same or higher level
        local next_heading_re="^##"
        if [[ $in_section -eq 1 ]] && [[ "$line" =~ $next_heading_re ]]; then
            break
        fi

        if [[ $in_section -eq 1 ]] && [[ -n "$line" ]]; then
            echo "$line"
            lines_out=$((lines_out + 1))
            if [[ $lines_out -ge $max_lines ]]; then
                break
            fi
        fi
    done < "$gov_file"
}

# Generate agent roster as bullet list
_amd_agent_roster() {
    for agent_file in "${RDF_CANONICAL}/agents"/*.md; do
        [[ -f "$agent_file" ]] || continue
        local agent_name
        agent_name="$(basename "$agent_file" .md)"
        local agent_desc
        agent_desc="$(sed -n '/^[^#[:space:]]/{ p; q; }' "$agent_file")"
        [[ -z "$agent_desc" ]] && agent_desc="Specialized agent"
        # Truncate long descriptions
        if [[ ${#agent_desc} -gt 100 ]]; then
            agent_desc="${agent_desc:0:97}..."
        fi
        echo "- **${agent_name}**: ${agent_desc}"
    done
}

# Full AGENTS.md generation
amd_generate_all() {
    rdf_log "generating AGENTS.md (cross-tool)..."
    rdf_require_dir "$RDF_CANONICAL" "canonical directory"
    rdf_require_file "$_AMD_SECTIONS" "sections.json"
    rdf_require_bin jq

    # Clean output directory
    command rm -rf "$_AMD_OUTPUT_DIR"
    command mkdir -p "$_AMD_OUTPUT_DIR"

    local dst_file="${_AMD_OUTPUT_DIR}/AGENTS.md"
    local profiles_dir="${RDF_HOME}/profiles"
    local max_lines
    max_lines="$(jq -r '.max_lines' "$_AMD_SECTIONS")"

    {
        echo "# AGENTS.md — rfxn Development Framework"
        echo ""
        echo "Cross-tool project instructions. Generated by \`rdf generate agents-md\`."
        echo ""
    } > "$dst_file"

    # Process each section from sections.json
    local section_count
    section_count="$(jq '.sections | length' "$_AMD_SECTIONS")"
    local i=0

    while [[ $i -lt $section_count ]]; do
        local heading source
        heading="$(jq -r ".sections[$i].heading" "$_AMD_SECTIONS")"
        source="$(jq -r ".sections[$i].source" "$_AMD_SECTIONS")"

        echo "## ${heading}" >> "$dst_file"
        echo "" >> "$dst_file"

        case "$source" in
            static)
                local content
                content="$(jq -r ".sections[$i].content" "$_AMD_SECTIONS")"
                echo "$content" >> "$dst_file"
                ;;
            governance)
                local profile extract gov_file
                profile="$(jq -r ".sections[$i].profile" "$_AMD_SECTIONS")"
                extract="$(jq -r ".sections[$i].extract" "$_AMD_SECTIONS")"
                gov_file="${profiles_dir}/${profile}/governance.md"
                _amd_extract_governance_section "$gov_file" "$extract" >> "$dst_file"
                ;;
            agents)
                _amd_agent_roster >> "$dst_file"
                ;;
            *)
                rdf_warn "agents-md: unknown section source: $source"
                ;;
        esac

        echo "" >> "$dst_file"
        i=$((i + 1))
    done

    # Verify line count
    local line_count
    line_count="$(wc -l < "$dst_file")"
    if [[ "$line_count" -gt "$max_lines" ]]; then
        rdf_warn "agents-md: AGENTS.md is ${line_count} lines (over ${max_lines} limit)"
    fi

    rdf_log "AGENTS.md generation complete: ${line_count} lines"
}
