#!/usr/bin/env bash
# adapters/agents-md/adapter.sh — AGENTS.md project composer
# (C) 2026 R-fx Networks <proj@rfxn.com>
# GNU GPL v2
# Sourced by lib/cmd/generate.sh — do not execute directly

# Requires: RDF_HOME, RDF_CANONICAL, RDF_ADAPTERS

_AMD_ADAPTER_DIR="${RDF_ADAPTERS}/agents-md"
_AMD_OUTPUT_DIR="${_AMD_ADAPTER_DIR}/output"
_AMD_MAX_BYTES=32768

# _amd_agent_roster — emit canonical agents as bullet list
_amd_agent_roster() {
    for agent_file in "${RDF_CANONICAL}/agents"/*.md; do
        [[ -f "$agent_file" ]] || continue
        local agent_name
        agent_name="$(basename "$agent_file" .md)"
        local agent_desc
        agent_desc="$(sed -n '/^[^#[:space:]]/{ p; q; }' "$agent_file")"
        [[ -z "$agent_desc" ]] && agent_desc="Specialized agent"
        if [[ ${#agent_desc} -gt 100 ]]; then
            agent_desc="${agent_desc:0:97}..."
        fi
        echo "- **${agent_name}**: ${agent_desc}"
    done
}

# _amd_context_source root — echo the project-context file: root/CLAUDE.md,
# else root/.rdf/governance/index.md, else nothing (caller falls back to a stub).
_amd_context_source() {
    local root="$1"
    if [[ -f "${root}/CLAUDE.md" ]]; then
        printf '%s\n' "${root}/CLAUDE.md"
    elif [[ -f "${root}/.rdf/governance/index.md" ]]; then
        printf '%s\n' "${root}/.rdf/governance/index.md"
    fi
}

# amd_compose root dst — write dst: header, root's own context (CLAUDE.md ->
# governance index -> stub), an Agent Skills pointer, and the agent roster.
# Refuses a root without .git unless root is RDF_HOME (the self-output case).
amd_compose() {
    local root="$1" dst="$2"
    rdf_require_dir "$root" "project root"

    local root_canon rdf_home_canon
    root_canon="$(rdf_canonical_path "$root")"
    rdf_home_canon="$(rdf_canonical_path "$RDF_HOME")"
    if [[ "$root_canon" != "$rdf_home_canon" ]] && [[ ! -d "${root}/.git" ]]; then
        rdf_die "agents-md: project root is not a git repository: ${root}"
    fi

    local repo_name
    repo_name="$(basename "$root_canon")"

    command mkdir -p "$(dirname "$dst")"

    local ctx_src
    ctx_src="$(_amd_context_source "$root")"

    {
        echo "# AGENTS.md — ${repo_name}"
        echo ""
        echo "Generated by \`rdf generate agents-md\` — do not edit directly."
        echo ""
        if [[ -n "$ctx_src" ]]; then
            command cat "$ctx_src"
        else
            rdf_warn "agents-md: no CLAUDE.md or .rdf/governance/index.md under ${root} — writing a minimal stub"
            echo "No project-specific governance found. Add a CLAUDE.md at the repo"
            echo "root to populate this section."
        fi
        echo ""
        echo "## Agent Skills"
        echo ""
        echo "Slash-command skills live under \`.agents/skills/\` — generate them with"
        echo "\`rdf generate agent-skills\`. Codex and Antigravity read that directory"
        echo "natively."
        echo ""
        echo "## Agent Roster"
        echo ""
        _amd_agent_roster
    } > "$dst"

    local size
    size="$(wc -c < "$dst")"
    if [[ "$size" -gt "$_AMD_MAX_BYTES" ]]; then
        rdf_warn "agents-md: AGENTS.md is ${size} bytes (over ${_AMD_MAX_BYTES} limit)"
    fi
    rdf_log "agents-md: wrote AGENTS.md (${size} bytes)"
}

# amd_generate_all [root] — compose the tracked AGENTS.md; root defaults to
# RDF_HOME, so a bare 'rdf generate agents-md' regenerates the self output.
amd_generate_all() {
    local root="${1:-$RDF_HOME}"
    rdf_log "generating AGENTS.md (cross-tool)..."
    amd_compose "$root" "${_AMD_OUTPUT_DIR}/AGENTS.md"
}
