#!/usr/bin/env bash
# adapters/gemini-cli/adapter.sh — Gemini CLI adapter
# (C) 2026 R-fx Networks <proj@rfxn.com>
# GNU GPL v2
# Sourced by lib/cmd/generate.sh — do not execute directly

# Requires: RDF_HOME, RDF_CANONICAL, RDF_ADAPTERS, jq

_GEM_ADAPTER_DIR="${RDF_ADAPTERS}/gemini-cli"
_GEM_OUTPUT_DIR="${_GEM_ADAPTER_DIR}/output"
_GEM_AGENT_META="${_GEM_ADAPTER_DIR}/agent-meta.json"
_GEM_COMMAND_META="${_GEM_ADAPTER_DIR}/command-meta.json"

# Generate YAML frontmatter for a Gemini CLI agent
# Args: $1 = canonical agent basename (no extension)
# Output: YAML frontmatter to stdout, or return 1 if agent not in metadata
_gem_agent_frontmatter() {
    local agent="$1"
    local name desc

    # Check if agent exists in metadata
    if ! jq -e --arg a "$agent" '.[$a]' "$_GEM_AGENT_META" >/dev/null 2>&1; then
        rdf_warn "no Gemini metadata for agent: $agent — copying without frontmatter"
        return 1
    fi

    name="$(jq -r --arg a "$agent" '.[$a].name' "$_GEM_AGENT_META")"
    desc="$(jq -r --arg a "$agent" '.[$a].description' "$_GEM_AGENT_META")"

    echo "---"
    echo "name: ${name}"
    echo "description: \"${desc}\""
    echo "---"
}

# Generate all Gemini CLI agent files
# Reads canonical/agents/*.md + agent-meta.json -> output/.gemini/agents/*.md
gem_generate_agents() {
    local src_dir="${RDF_CANONICAL}/agents"
    local dst_dir="${_GEM_OUTPUT_DIR}/.gemini/agents"
    local count=0

    command mkdir -p "$dst_dir"

    for src_file in "${src_dir}"/*.md; do
        [[ -f "$src_file" ]] || continue
        local basename_f
        basename_f="$(basename "$src_file" .md)"
        local dst_file="${dst_dir}/${basename_f}.md"

        # Generate frontmatter + canonical body
        if _gem_agent_frontmatter "$basename_f" > "${dst_file}.tmp" 2>/dev/null; then
            echo "" >> "${dst_file}.tmp"
            cat "$src_file" >> "${dst_file}.tmp"
            command mv "${dst_file}.tmp" "$dst_file"
        else
            # No metadata — copy canonical body with minimal frontmatter
            {
                echo "---"
                echo "name: ${basename_f}"
                echo "description: \"RDF agent: ${basename_f}\""
                echo "---"
                echo ""
                cat "$src_file"
            } > "$dst_file"
        fi
        count=$((count + 1))
    done
    rdf_log "gemini-cli: generated ${count} agent files"
}

# Generate a single TOML command file from canonical markdown
# Args: $1 = canonical command markdown path, $2 = destination .toml path
_gem_write_command_toml() {
    local src_file="$1"
    local dst_file="$2"
    local basename_f
    basename_f="$(basename "$src_file" .md)"

    # Get description from metadata, or extract first sentence
    local desc
    desc="$(jq -r --arg c "$basename_f" '.[$c] // empty' "$_GEM_COMMAND_META" 2>/dev/null)"

    if [[ -z "$desc" ]]; then
        # Extract first non-empty line as description, truncate to 80 chars
        desc="$(sed -n '/^[^#[:space:]]/{ s/[[:space:]]*$//; p; q; }' "$src_file")"
        if [[ ${#desc} -gt 80 ]]; then
            desc="${desc:0:77}..."
        fi
        # Fallback if still empty
        [[ -z "$desc" ]] && desc="RDF command: ${basename_f}"
    fi

    # Read full canonical body as the prompt
    local body
    body="$(< "$src_file")"

    # Write TOML
    {
        echo "# Generated by rdf generate gemini-cli — do not edit"
        echo "# Source: canonical/commands/${basename_f}.md"
        echo ""
        echo "description = \"${desc}\""
        echo ""
        # Use TOML multi-line literal string for prompt
        echo 'prompt = """'
        echo "${body}"
        echo '"""'
    } > "$dst_file"
}

# Generate all Gemini CLI command files
# Reads canonical/commands/*.md -> output/.gemini/commands/*.toml
gem_generate_commands() {
    local src_dir="${RDF_CANONICAL}/commands"
    local dst_dir="${_GEM_OUTPUT_DIR}/.gemini/commands"
    local count=0

    command mkdir -p "$dst_dir"

    for src_file in "${src_dir}"/*.md; do
        [[ -f "$src_file" ]] || continue
        local basename_f
        basename_f="$(basename "$src_file" .md)"
        local dst_file="${dst_dir}/${basename_f}.toml"

        _gem_write_command_toml "$src_file" "$dst_file"
        count=$((count + 1))
    done
    rdf_log "gemini-cli: generated ${count} command TOML files"
}

# Generate GEMINI.md from profile governance docs
# Produces a single GEMINI.md with concatenated governance from active profiles
gem_generate_context() {
    local dst_file="${_GEM_OUTPUT_DIR}/.gemini/GEMINI.md"
    local profiles_dir="${RDF_HOME}/profiles"

    command mkdir -p "$(dirname "$dst_file")"

    {
        echo "# RDF Project Governance — Gemini CLI Context"
        echo ""
        echo "Generated by \`rdf generate gemini-cli\` — do not edit directly."
        echo "Source: rdf/profiles/*/governance.md"
        echo ""
    } > "$dst_file"

    # Concatenate active profile governance docs
    local active
    active="$(rdf_get_active_profiles)"

    while IFS= read -r profile; do
        [[ -z "$profile" ]] && continue
        local gov_file="${profiles_dir}/${profile}/governance.md"
        if [[ -f "$gov_file" ]]; then
            {
                echo ""
                echo "---"
                echo ""
                cat "$gov_file"
            } >> "$dst_file"
        else
            rdf_warn "gemini-cli: governance.md not found for profile: $profile"
        fi
    done <<< "$active"

    rdf_log "gemini-cli: generated GEMINI.md"
}

# Generate script files (direct copy — scripts are tool-agnostic)
gem_generate_scripts() {
    local src_dir="${RDF_CANONICAL}/scripts"
    local dst_dir="${_GEM_OUTPUT_DIR}/scripts"
    local count=0

    command mkdir -p "$dst_dir"

    for src_file in "${src_dir}"/*.sh; do
        [[ -f "$src_file" ]] || continue
        local basename_f
        basename_f="$(basename "$src_file")"
        command cp "$src_file" "${dst_dir}/${basename_f}"
        chmod +x "${dst_dir}/${basename_f}"
        count=$((count + 1))
    done
    rdf_log "gemini-cli: generated ${count} script files"
}

# Full Gemini CLI generation pipeline
gem_generate_all() {
    rdf_log "generating Gemini CLI adapter output..."
    rdf_require_dir "$RDF_CANONICAL" "canonical directory"
    rdf_require_file "$_GEM_AGENT_META" "gemini-cli agent-meta.json"
    rdf_require_bin jq

    local _output_final="$_GEM_OUTPUT_DIR"
    local _output_new="${_GEM_OUTPUT_DIR}.new"
    local _output_old="${_GEM_OUTPUT_DIR}.old"

    # Build into staging directory
    command rm -rf "$_output_new"
    command mkdir -p "$_output_new"
    _GEM_OUTPUT_DIR="$_output_new"

    gem_generate_agents
    gem_generate_commands
    gem_generate_context
    gem_generate_scripts

    # Atomic swap
    _GEM_OUTPUT_DIR="$_output_final"
    command rm -rf "$_output_old"
    if [[ -d "$_output_final" ]]; then
        command mv "$_output_final" "$_output_old"
    fi
    command mv "$_output_new" "$_output_final"
    command rm -rf "$_output_old"

    local agent_count command_count script_count
    agent_count="$(find "${_GEM_OUTPUT_DIR}/.gemini/agents" -name '*.md' 2>/dev/null | wc -l)"
    command_count="$(find "${_GEM_OUTPUT_DIR}/.gemini/commands" -name '*.toml' 2>/dev/null | wc -l)"
    script_count="$(find "${_GEM_OUTPUT_DIR}/scripts" -name '*.sh' 2>/dev/null | wc -l)"

    rdf_log "Gemini CLI generation complete: ${agent_count} agents, ${command_count} commands, ${script_count} scripts"
}
